name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: 
      image: google/dart:latest  
    steps:
      - uses: actions/checkout@master   

      - name: Run tests
        run: |
          pub version
          pub get
          pub test